### ISSUE TITLE
When you delete workflow conditions, you can't save the workflow anymore

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#968] opened 2020-11-25 09:03 UTC

**Comment by joebordes** [comment] 2020-11-25 09:45
I cannot reproduce this. Neither in the master branch nor the denorm branch.
Please check that you have the latest version of javascript (cache)
If you are talking about a particular workflow TASK, please give more details. Also, try to reproduce in the demo and point to the failing workflow.

**Comment by Luke1982** [comment] 2020-12-09 16:15
No this was a workflow, not a task. The installation is quite recent (maybe a month old), but I'll try and get some more information soon.

**Comment by joebordes** [comment] 2021-11-02 22:14
closing this one

**Closed by joebordes** 2021-11-02 22:14 UTC
Labels: bug
