### ISSUE TITLE
Ticket created from mailscanner not assign correctly to a group

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#1052] opened 2021-04-27 15:15 UTC
Rule for created a new ticket origin in Mailscanner always not assigned correclty when uses a group in assigned to field

The rule for creating a new ticket source in Mailscanner is not assigned correctly when using a group in the field assigned to
![image](https://user-images.githubusercontent.com/47395137/116266819-38617500-a752-11eb-8fba-aea362dbc9f6.png)

**Comment by joebordes** [comment] 2021-05-13 08:59
We couldn't reproduce this issue once we eliminated the `Update AssignedTo` workflow task from the official development test data install. In other words, if you are working with the official coreBOS Tests database, there is a workflow there that forces the tickets to be assigned to a user. That is specifically for testing that functionality. Once we deactivate that workflow, the tickets are assigned correctly to the group.

Can you verify if there is some workflow in your install that is changing the assignment?

**Closed** 2021-10-16 16:47 UTC
